/**
 * PassHub API
 * PassHub API documentation
 *
 * OpenAPI spec version: 1.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/OrderItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./OrderItem'));
  } else {
    // Browser globals (root is window)
    if (!root.PassHubApi) {
      root.PassHubApi = {};
    }
    root.PassHubApi.GroupEntryDTO = factory(root.PassHubApi.ApiClient, root.PassHubApi.OrderItem);
  }
}(this, function(ApiClient, OrderItem) {
  'use strict';




  /**
   * The GroupEntryDTO model module.
   * @module model/GroupEntryDTO
   * @version 1.1
   */

  /**
   * Constructs a new <code>GroupEntryDTO</code>.
   * @alias module:model/GroupEntryDTO
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>GroupEntryDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GroupEntryDTO} obj Optional instance to populate.
   * @return {module:model/GroupEntryDTO} The populated <code>GroupEntryDTO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('groupName')) {
        obj['groupName'] = ApiClient.convertToType(data['groupName'], 'String');
      }
      if (data.hasOwnProperty('items')) {
        obj['items'] = ApiClient.convertToType(data['items'], [OrderItem]);
      }
      if (data.hasOwnProperty('voucherPerPerson')) {
        obj['voucherPerPerson'] = ApiClient.convertToType(data['voucherPerPerson'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {String} groupName
   */
  exports.prototype['groupName'] = undefined;
  /**
   * @member {Array.<module:model/OrderItem>} items
   */
  exports.prototype['items'] = undefined;
  /**
   * @member {Boolean} voucherPerPerson
   */
  exports.prototype['voucherPerPerson'] = undefined;



  return exports;
}));


