/**
 * PassHub API
 * PassHub API documentation
 *
 * OpenAPI spec version: 1.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DeliveryDTO', 'model/GroupEntryDTO', 'model/UserDTO'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DeliveryDTO'), require('./GroupEntryDTO'), require('./UserDTO'));
  } else {
    // Browser globals (root is window)
    if (!root.PassHubApi) {
      root.PassHubApi = {};
    }
    root.PassHubApi.OrderRecordExtendDTO = factory(root.PassHubApi.ApiClient, root.PassHubApi.DeliveryDTO, root.PassHubApi.GroupEntryDTO, root.PassHubApi.UserDTO);
  }
}(this, function(ApiClient, DeliveryDTO, GroupEntryDTO, UserDTO) {
  'use strict';




  /**
   * The OrderRecordExtendDTO model module.
   * @module model/OrderRecordExtendDTO
   * @version 1.1
   */

  /**
   * Constructs a new <code>OrderRecordExtendDTO</code>.
   * @alias module:model/OrderRecordExtendDTO
   * @class
   */
  var exports = function() {
    var _this = this;

















  };

  /**
   * Constructs a <code>OrderRecordExtendDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderRecordExtendDTO} obj Optional instance to populate.
   * @return {module:model/OrderRecordExtendDTO} The populated <code>OrderRecordExtendDTO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('amount')) {
        obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
      }
      if (data.hasOwnProperty('cellPhoneNumber')) {
        obj['cellPhoneNumber'] = ApiClient.convertToType(data['cellPhoneNumber'], 'String');
      }
      if (data.hasOwnProperty('created')) {
        obj['created'] = ApiClient.convertToType(data['created'], 'String');
      }
      if (data.hasOwnProperty('createdBy')) {
        obj['createdBy'] = UserDTO.constructFromObject(data['createdBy']);
      }
      if (data.hasOwnProperty('customerEmail')) {
        obj['customerEmail'] = ApiClient.convertToType(data['customerEmail'], 'String');
      }
      if (data.hasOwnProperty('customerId')) {
        obj['customerId'] = ApiClient.convertToType(data['customerId'], 'String');
      }
      if (data.hasOwnProperty('delivery')) {
        obj['delivery'] = DeliveryDTO.constructFromObject(data['delivery']);
      }
      if (data.hasOwnProperty('deliveryMethod')) {
        obj['deliveryMethod'] = ApiClient.convertToType(data['deliveryMethod'], 'String');
      }
      if (data.hasOwnProperty('groups')) {
        obj['groups'] = ApiClient.convertToType(data['groups'], [GroupEntryDTO]);
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('isTest')) {
        obj['isTest'] = ApiClient.convertToType(data['isTest'], 'Boolean');
      }
      if (data.hasOwnProperty('isValidated')) {
        obj['isValidated'] = ApiClient.convertToType(data['isValidated'], 'Boolean');
      }
      if (data.hasOwnProperty('orderId')) {
        obj['orderId'] = ApiClient.convertToType(data['orderId'], 'String');
      }
      if (data.hasOwnProperty('originatorOrderId')) {
        obj['originatorOrderId'] = ApiClient.convertToType(data['originatorOrderId'], 'String');
      }
      if (data.hasOwnProperty('originiator')) {
        obj['originiator'] = ApiClient.convertToType(data['originiator'], 'String');
      }
      if (data.hasOwnProperty('vendorOrderId')) {
        obj['vendorOrderId'] = ApiClient.convertToType(data['vendorOrderId'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} amount
   */
  exports.prototype['amount'] = undefined;
  /**
   * @member {String} cellPhoneNumber
   */
  exports.prototype['cellPhoneNumber'] = undefined;
  /**
   * @member {String} created
   */
  exports.prototype['created'] = undefined;
  /**
   * @member {module:model/UserDTO} createdBy
   */
  exports.prototype['createdBy'] = undefined;
  /**
   * @member {String} customerEmail
   */
  exports.prototype['customerEmail'] = undefined;
  /**
   * @member {String} customerId
   */
  exports.prototype['customerId'] = undefined;
  /**
   * @member {module:model/DeliveryDTO} delivery
   */
  exports.prototype['delivery'] = undefined;
  /**
   * @member {module:model/OrderRecordExtendDTO.DeliveryMethodEnum} deliveryMethod
   */
  exports.prototype['deliveryMethod'] = undefined;
  /**
   * @member {Array.<module:model/GroupEntryDTO>} groups
   */
  exports.prototype['groups'] = undefined;
  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Boolean} isTest
   */
  exports.prototype['isTest'] = undefined;
  /**
   * @member {Boolean} isValidated
   */
  exports.prototype['isValidated'] = undefined;
  /**
   * @member {String} orderId
   */
  exports.prototype['orderId'] = undefined;
  /**
   * @member {String} originatorOrderId
   */
  exports.prototype['originatorOrderId'] = undefined;
  /**
   * @member {String} originiator
   */
  exports.prototype['originiator'] = undefined;
  /**
   * @member {String} vendorOrderId
   */
  exports.prototype['vendorOrderId'] = undefined;


  /**
   * Allowed values for the <code>deliveryMethod</code> property.
   * @enum {String}
   * @readonly
   */
  exports.DeliveryMethodEnum = {
    /**
     * value: "DIGITAL"
     * @const
     */
    "DIGITAL": "DIGITAL",
    /**
     * value: "SHIPPING"
     * @const
     */
    "SHIPPING": "SHIPPING"  };


  return exports;
}));


