/**
 * PassHub API
 * PassHub API documentation
 *
 * OpenAPI spec version: 1.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SimpleMetadata', 'model/SimpleProductDTO', 'model/UserDTO'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SimpleMetadata'), require('./SimpleProductDTO'), require('./UserDTO'));
  } else {
    // Browser globals (root is window)
    if (!root.PassHubApi) {
      root.PassHubApi = {};
    }
    root.PassHubApi.OrderItem = factory(root.PassHubApi.ApiClient, root.PassHubApi.SimpleMetadata, root.PassHubApi.SimpleProductDTO, root.PassHubApi.UserDTO);
  }
}(this, function(ApiClient, SimpleMetadata, SimpleProductDTO, UserDTO) {
  'use strict';




  /**
   * The OrderItem model module.
   * @module model/OrderItem
   * @version 1.1
   */

  /**
   * Constructs a new <code>OrderItem</code>.
   * @alias module:model/OrderItem
   * @class
   */
  var exports = function() {
    var _this = this;



























  };

  /**
   * Constructs a <code>OrderItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderItem} obj Optional instance to populate.
   * @return {module:model/OrderItem} The populated <code>OrderItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('aliasVoucherIds')) {
        obj['aliasVoucherIds'] = ApiClient.convertToType(data['aliasVoucherIds'], ['String']);
      }
      if (data.hasOwnProperty('contractHolderId')) {
        obj['contractHolderId'] = ApiClient.convertToType(data['contractHolderId'], 'String');
      }
      if (data.hasOwnProperty('contractHolderName')) {
        obj['contractHolderName'] = ApiClient.convertToType(data['contractHolderName'], 'String');
      }
      if (data.hasOwnProperty('customerCompany')) {
        obj['customerCompany'] = ApiClient.convertToType(data['customerCompany'], 'String');
      }
      if (data.hasOwnProperty('customerEmail')) {
        obj['customerEmail'] = ApiClient.convertToType(data['customerEmail'], 'String');
      }
      if (data.hasOwnProperty('customerName')) {
        obj['customerName'] = ApiClient.convertToType(data['customerName'], 'String');
      }
      if (data.hasOwnProperty('customerUid')) {
        obj['customerUid'] = ApiClient.convertToType(data['customerUid'], 'String');
      }
      if (data.hasOwnProperty('expireDate')) {
        obj['expireDate'] = ApiClient.convertToType(data['expireDate'], 'String');
      }
      if (data.hasOwnProperty('expiryDateBeforeValidtion')) {
        obj['expiryDateBeforeValidtion'] = ApiClient.convertToType(data['expiryDateBeforeValidtion'], 'String');
      }
      if (data.hasOwnProperty('groupName')) {
        obj['groupName'] = ApiClient.convertToType(data['groupName'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('initVoucherId')) {
        obj['initVoucherId'] = ApiClient.convertToType(data['initVoucherId'], 'String');
      }
      if (data.hasOwnProperty('isCanceled')) {
        obj['isCanceled'] = ApiClient.convertToType(data['isCanceled'], 'Boolean');
      }
      if (data.hasOwnProperty('isValidated')) {
        obj['isValidated'] = ApiClient.convertToType(data['isValidated'], 'Boolean');
      }
      if (data.hasOwnProperty('metadata')) {
        obj['metadata'] = SimpleMetadata.constructFromObject(data['metadata']);
      }
      if (data.hasOwnProperty('originatorVoucherId')) {
        obj['originatorVoucherId'] = ApiClient.convertToType(data['originatorVoucherId'], 'String');
      }
      if (data.hasOwnProperty('pricePaid')) {
        obj['pricePaid'] = ApiClient.convertToType(data['pricePaid'], 'Number');
      }
      if (data.hasOwnProperty('product')) {
        obj['product'] = SimpleProductDTO.constructFromObject(data['product']);
      }
      if (data.hasOwnProperty('quantity')) {
        obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
      }
      if (data.hasOwnProperty('sku')) {
        obj['sku'] = ApiClient.convertToType(data['sku'], 'String');
      }
      if (data.hasOwnProperty('tourDate')) {
        obj['tourDate'] = ApiClient.convertToType(data['tourDate'], 'String');
      }
      if (data.hasOwnProperty('updated')) {
        obj['updated'] = ApiClient.convertToType(data['updated'], 'String');
      }
      if (data.hasOwnProperty('updatedBy')) {
        obj['updatedBy'] = UserDTO.constructFromObject(data['updatedBy']);
      }
      if (data.hasOwnProperty('validationId')) {
        obj['validationId'] = ApiClient.convertToType(data['validationId'], 'String');
      }
      if (data.hasOwnProperty('vendorVoucherId')) {
        obj['vendorVoucherId'] = ApiClient.convertToType(data['vendorVoucherId'], 'String');
      }
      if (data.hasOwnProperty('voucherId')) {
        obj['voucherId'] = ApiClient.convertToType(data['voucherId'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<String>} aliasVoucherIds
   */
  exports.prototype['aliasVoucherIds'] = undefined;
  /**
   * @member {String} contractHolderId
   */
  exports.prototype['contractHolderId'] = undefined;
  /**
   * @member {String} contractHolderName
   */
  exports.prototype['contractHolderName'] = undefined;
  /**
   * @member {String} customerCompany
   */
  exports.prototype['customerCompany'] = undefined;
  /**
   * @member {String} customerEmail
   */
  exports.prototype['customerEmail'] = undefined;
  /**
   * @member {String} customerName
   */
  exports.prototype['customerName'] = undefined;
  /**
   * @member {String} customerUid
   */
  exports.prototype['customerUid'] = undefined;
  /**
   * @member {String} expireDate
   */
  exports.prototype['expireDate'] = undefined;
  /**
   * @member {String} expiryDateBeforeValidtion
   */
  exports.prototype['expiryDateBeforeValidtion'] = undefined;
  /**
   * @member {String} groupName
   */
  exports.prototype['groupName'] = undefined;
  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} initVoucherId
   */
  exports.prototype['initVoucherId'] = undefined;
  /**
   * @member {Boolean} isCanceled
   */
  exports.prototype['isCanceled'] = undefined;
  /**
   * @member {Boolean} isValidated
   */
  exports.prototype['isValidated'] = undefined;
  /**
   * @member {module:model/SimpleMetadata} metadata
   */
  exports.prototype['metadata'] = undefined;
  /**
   * @member {String} originatorVoucherId
   */
  exports.prototype['originatorVoucherId'] = undefined;
  /**
   * @member {Number} pricePaid
   */
  exports.prototype['pricePaid'] = undefined;
  /**
   * @member {module:model/SimpleProductDTO} product
   */
  exports.prototype['product'] = undefined;
  /**
   * @member {Number} quantity
   */
  exports.prototype['quantity'] = undefined;
  /**
   * @member {String} sku
   */
  exports.prototype['sku'] = undefined;
  /**
   * @member {String} tourDate
   */
  exports.prototype['tourDate'] = undefined;
  /**
   * @member {String} updated
   */
  exports.prototype['updated'] = undefined;
  /**
   * @member {module:model/UserDTO} updatedBy
   */
  exports.prototype['updatedBy'] = undefined;
  /**
   * @member {String} validationId
   */
  exports.prototype['validationId'] = undefined;
  /**
   * @member {String} vendorVoucherId
   */
  exports.prototype['vendorVoucherId'] = undefined;
  /**
   * @member {String} voucherId
   */
  exports.prototype['voucherId'] = undefined;



  return exports;
}));


