/**
 * PassHub API
 * PassHub API documentation
 *
 * OpenAPI spec version: 1.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/VoucherPattern'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./VoucherPattern'));
  } else {
    // Browser globals (root is window)
    if (!root.PassHubApi) {
      root.PassHubApi = {};
    }
    root.PassHubApi.ProductDTO = factory(root.PassHubApi.ApiClient, root.PassHubApi.VoucherPattern);
  }
}(this, function(ApiClient, VoucherPattern) {
  'use strict';




  /**
   * The ProductDTO model module.
   * @module model/ProductDTO
   * @version 1.1
   */

  /**
   * Constructs a new <code>ProductDTO</code>.
   * @alias module:model/ProductDTO
   * @class
   */
  var exports = function() {
    var _this = this;






















  };

  /**
   * Constructs a <code>ProductDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProductDTO} obj Optional instance to populate.
   * @return {module:model/ProductDTO} The populated <code>ProductDTO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('allowRecharge')) {
        obj['allowRecharge'] = ApiClient.convertToType(data['allowRecharge'], 'Boolean');
      }
      if (data.hasOwnProperty('customerType')) {
        obj['customerType'] = ApiClient.convertToType(data['customerType'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('packageProductId')) {
        obj['packageProductId'] = ApiClient.convertToType(data['packageProductId'], 'String');
      }
      if (data.hasOwnProperty('price')) {
        obj['price'] = ApiClient.convertToType(data['price'], 'Number');
      }
      if (data.hasOwnProperty('productId')) {
        obj['productId'] = ApiClient.convertToType(data['productId'], 'String');
      }
      if (data.hasOwnProperty('rechargePrice')) {
        obj['rechargePrice'] = ApiClient.convertToType(data['rechargePrice'], 'Number');
      }
      if (data.hasOwnProperty('retailPrice')) {
        obj['retailPrice'] = ApiClient.convertToType(data['retailPrice'], 'Number');
      }
      if (data.hasOwnProperty('sku')) {
        obj['sku'] = ApiClient.convertToType(data['sku'], 'String');
      }
      if (data.hasOwnProperty('subProductId')) {
        obj['subProductId'] = ApiClient.convertToType(data['subProductId'], 'String');
      }
      if (data.hasOwnProperty('tags')) {
        obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
      }
      if (data.hasOwnProperty('timezone')) {
        obj['timezone'] = ApiClient.convertToType(data['timezone'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('validValue')) {
        obj['validValue'] = ApiClient.convertToType(data['validValue'], 'Number');
      }
      if (data.hasOwnProperty('validationTag')) {
        obj['validationTag'] = ApiClient.convertToType(data['validationTag'], 'String');
      }
      if (data.hasOwnProperty('vendorAccountId')) {
        obj['vendorAccountId'] = ApiClient.convertToType(data['vendorAccountId'], 'String');
      }
      if (data.hasOwnProperty('vendorName')) {
        obj['vendorName'] = ApiClient.convertToType(data['vendorName'], 'String');
      }
      if (data.hasOwnProperty('vendorSku')) {
        obj['vendorSku'] = ApiClient.convertToType(data['vendorSku'], 'String');
      }
      if (data.hasOwnProperty('voucherPattern')) {
        obj['voucherPattern'] = VoucherPattern.constructFromObject(data['voucherPattern']);
      }
      if (data.hasOwnProperty('voucherType')) {
        obj['voucherType'] = ApiClient.convertToType(data['voucherType'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Boolean} allowRecharge
   */
  exports.prototype['allowRecharge'] = undefined;
  /**
   * @member {module:model/ProductDTO.CustomerTypeEnum} customerType
   */
  exports.prototype['customerType'] = undefined;
  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} packageProductId
   */
  exports.prototype['packageProductId'] = undefined;
  /**
   * @member {Number} price
   */
  exports.prototype['price'] = undefined;
  /**
   * @member {String} productId
   */
  exports.prototype['productId'] = undefined;
  /**
   * @member {Number} rechargePrice
   */
  exports.prototype['rechargePrice'] = undefined;
  /**
   * @member {Number} retailPrice
   */
  exports.prototype['retailPrice'] = undefined;
  /**
   * @member {String} sku
   */
  exports.prototype['sku'] = undefined;
  /**
   * @member {String} subProductId
   */
  exports.prototype['subProductId'] = undefined;
  /**
   * @member {Array.<String>} tags
   */
  exports.prototype['tags'] = undefined;
  /**
   * @member {String} timezone
   */
  exports.prototype['timezone'] = undefined;
  /**
   * @member {module:model/ProductDTO.TypeEnum} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {Number} validValue
   */
  exports.prototype['validValue'] = undefined;
  /**
   * @member {String} validationTag
   */
  exports.prototype['validationTag'] = undefined;
  /**
   * @member {String} vendorAccountId
   */
  exports.prototype['vendorAccountId'] = undefined;
  /**
   * @member {String} vendorName
   */
  exports.prototype['vendorName'] = undefined;
  /**
   * @member {String} vendorSku
   */
  exports.prototype['vendorSku'] = undefined;
  /**
   * @member {module:model/VoucherPattern} voucherPattern
   */
  exports.prototype['voucherPattern'] = undefined;
  /**
   * @member {module:model/ProductDTO.VoucherTypeEnum} voucherType
   */
  exports.prototype['voucherType'] = undefined;


  /**
   * Allowed values for the <code>customerType</code> property.
   * @enum {String}
   * @readonly
   */
  exports.CustomerTypeEnum = {
    /**
     * value: "ADULT"
     * @const
     */
    "ADULT": "ADULT",
    /**
     * value: "CHILD"
     * @const
     */
    "CHILD": "CHILD",
    /**
     * value: "SENIOR"
     * @const
     */
    "SENIOR": "SENIOR"  };

  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "BASIC_SINGLE"
     * @const
     */
    "BASIC_SINGLE": "BASIC_SINGLE",
    /**
     * value: "BASIC_VALID_HOURS"
     * @const
     */
    "BASIC_VALID_HOURS": "BASIC_VALID_HOURS",
    /**
     * value: "PASS_LIMITED"
     * @const
     */
    "PASS_LIMITED": "PASS_LIMITED",
    /**
     * value: "PASS_UNLIMITED"
     * @const
     */
    "PASS_UNLIMITED": "PASS_UNLIMITED",
    /**
     * value: "PASS_CALENDAR"
     * @const
     */
    "PASS_CALENDAR": "PASS_CALENDAR",
    /**
     * value: "FLEXPASS"
     * @const
     */
    "FLEXPASS": "FLEXPASS",
    /**
     * value: "PASS_CURRENCY"
     * @const
     */
    "PASS_CURRENCY": "PASS_CURRENCY"  };

  /**
   * Allowed values for the <code>voucherType</code> property.
   * @enum {String}
   * @readonly
   */
  exports.VoucherTypeEnum = {
    /**
     * value: "DEFAULT"
     * @const
     */
    "DEFAULT": "DEFAULT",
    /**
     * value: "CUSTOM"
     * @const
     */
    "CUSTOM": "CUSTOM"  };


  return exports;
}));


