/**
 * PassHub API
 * PassHub API documentation
 *
 * OpenAPI spec version: 1.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PassHubApi) {
      root.PassHubApi = {};
    }
    root.PassHubApi.ProductSuggestion = factory(root.PassHubApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ProductSuggestion model module.
   * @module model/ProductSuggestion
   * @version 1.1
   */

  /**
   * Constructs a new <code>ProductSuggestion</code>.
   * @alias module:model/ProductSuggestion
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>ProductSuggestion</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProductSuggestion} obj Optional instance to populate.
   * @return {module:model/ProductSuggestion} The populated <code>ProductSuggestion</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('connectionType')) {
        obj['connectionType'] = ApiClient.convertToType(data['connectionType'], 'String');
      }
      if (data.hasOwnProperty('customerType')) {
        obj['customerType'] = ApiClient.convertToType(data['customerType'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('productTag')) {
        obj['productTag'] = ApiClient.convertToType(data['productTag'], 'String');
      }
      if (data.hasOwnProperty('sku')) {
        obj['sku'] = ApiClient.convertToType(data['sku'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/ProductSuggestion.ConnectionTypeEnum} connectionType
   */
  exports.prototype['connectionType'] = undefined;
  /**
   * @member {module:model/ProductSuggestion.CustomerTypeEnum} customerType
   */
  exports.prototype['customerType'] = undefined;
  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} productTag
   */
  exports.prototype['productTag'] = undefined;
  /**
   * @member {String} sku
   */
  exports.prototype['sku'] = undefined;


  /**
   * Allowed values for the <code>connectionType</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ConnectionTypeEnum = {
    /**
     * value: "INCLUDE"
     * @const
     */
    "INCLUDE": "INCLUDE",
    /**
     * value: "PASS"
     * @const
     */
    "PASS": "PASS"  };

  /**
   * Allowed values for the <code>customerType</code> property.
   * @enum {String}
   * @readonly
   */
  exports.CustomerTypeEnum = {
    /**
     * value: "ADULT"
     * @const
     */
    "ADULT": "ADULT",
    /**
     * value: "CHILD"
     * @const
     */
    "CHILD": "CHILD",
    /**
     * value: "SENIOR"
     * @const
     */
    "SENIOR": "SENIOR"  };


  return exports;
}));


