/**
 * PassHub API
 * PassHub API documentation
 *
 * OpenAPI spec version: 1.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RechargePromptEntry'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RechargePromptEntry'));
  } else {
    // Browser globals (root is window)
    if (!root.PassHubApi) {
      root.PassHubApi = {};
    }
    root.PassHubApi.RechargeProductGroup = factory(root.PassHubApi.ApiClient, root.PassHubApi.RechargePromptEntry);
  }
}(this, function(ApiClient, RechargePromptEntry) {
  'use strict';




  /**
   * The RechargeProductGroup model module.
   * @module model/RechargeProductGroup
   * @version 1.1
   */

  /**
   * Constructs a new <code>RechargeProductGroup</code>.
   * @alias module:model/RechargeProductGroup
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>RechargeProductGroup</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RechargeProductGroup} obj Optional instance to populate.
   * @return {module:model/RechargeProductGroup} The populated <code>RechargeProductGroup</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('entries')) {
        obj['entries'] = ApiClient.convertToType(data['entries'], [RechargePromptEntry]);
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('passProduct')) {
        obj['passProduct'] = ApiClient.convertToType(data['passProduct'], 'Boolean');
      }
      if (data.hasOwnProperty('price')) {
        obj['price'] = ApiClient.convertToType(data['price'], 'Number');
      }
      if (data.hasOwnProperty('productIds')) {
        obj['productIds'] = ApiClient.convertToType(data['productIds'], ['Number']);
      }
      if (data.hasOwnProperty('productTag')) {
        obj['productTag'] = ApiClient.convertToType(data['productTag'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/RechargePromptEntry>} entries
   */
  exports.prototype['entries'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {Boolean} passProduct
   */
  exports.prototype['passProduct'] = undefined;
  /**
   * @member {Number} price
   */
  exports.prototype['price'] = undefined;
  /**
   * @member {Array.<Number>} productIds
   */
  exports.prototype['productIds'] = undefined;
  /**
   * @member {String} productTag
   */
  exports.prototype['productTag'] = undefined;



  return exports;
}));


