/**
 * PassHub API
 * PassHub API documentation
 *
 * OpenAPI spec version: 1.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SimpleConnectedProductDTO'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SimpleConnectedProductDTO'));
  } else {
    // Browser globals (root is window)
    if (!root.PassHubApi) {
      root.PassHubApi = {};
    }
    root.PassHubApi.SimpleProductConnectionDTO = factory(root.PassHubApi.ApiClient, root.PassHubApi.SimpleConnectedProductDTO);
  }
}(this, function(ApiClient, SimpleConnectedProductDTO) {
  'use strict';




  /**
   * The SimpleProductConnectionDTO model module.
   * @module model/SimpleProductConnectionDTO
   * @version 1.1
   */

  /**
   * Constructs a new <code>SimpleProductConnectionDTO</code>.
   * @alias module:model/SimpleProductConnectionDTO
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>SimpleProductConnectionDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SimpleProductConnectionDTO} obj Optional instance to populate.
   * @return {module:model/SimpleProductConnectionDTO} The populated <code>SimpleProductConnectionDTO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('connectedProduct')) {
        obj['connectedProduct'] = SimpleConnectedProductDTO.constructFromObject(data['connectedProduct']);
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/SimpleConnectedProductDTO} connectedProduct
   */
  exports.prototype['connectedProduct'] = undefined;
  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {module:model/SimpleProductConnectionDTO.TypeEnum} type
   */
  exports.prototype['type'] = undefined;


  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "INCLUDE"
     * @const
     */
    "INCLUDE": "INCLUDE",
    /**
     * value: "PASS"
     * @const
     */
    "PASS": "PASS"  };


  return exports;
}));


