/**
 * PassHub API
 * PassHub API documentation
 *
 * OpenAPI spec version: 1.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Rule', 'model/SimpleProductConnectionDTO', 'model/UserDTO', 'model/VendorDTO', 'model/VoucherPattern'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Rule'), require('./SimpleProductConnectionDTO'), require('./UserDTO'), require('./VendorDTO'), require('./VoucherPattern'));
  } else {
    // Browser globals (root is window)
    if (!root.PassHubApi) {
      root.PassHubApi = {};
    }
    root.PassHubApi.SimpleProductDTO = factory(root.PassHubApi.ApiClient, root.PassHubApi.Rule, root.PassHubApi.SimpleProductConnectionDTO, root.PassHubApi.UserDTO, root.PassHubApi.VendorDTO, root.PassHubApi.VoucherPattern);
  }
}(this, function(ApiClient, Rule, SimpleProductConnectionDTO, UserDTO, VendorDTO, VoucherPattern) {
  'use strict';




  /**
   * The SimpleProductDTO model module.
   * @module model/SimpleProductDTO
   * @version 1.1
   */

  /**
   * Constructs a new <code>SimpleProductDTO</code>.
   * @alias module:model/SimpleProductDTO
   * @class
   */
  var exports = function() {
    var _this = this;
































  };

  /**
   * Constructs a <code>SimpleProductDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SimpleProductDTO} obj Optional instance to populate.
   * @return {module:model/SimpleProductDTO} The populated <code>SimpleProductDTO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('allowRecharge')) {
        obj['allowRecharge'] = ApiClient.convertToType(data['allowRecharge'], 'Boolean');
      }
      if (data.hasOwnProperty('countryCode')) {
        obj['countryCode'] = ApiClient.convertToType(data['countryCode'], 'String');
      }
      if (data.hasOwnProperty('customerType')) {
        obj['customerType'] = ApiClient.convertToType(data['customerType'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('includes')) {
        obj['includes'] = ApiClient.convertToType(data['includes'], [SimpleProductConnectionDTO]);
      }
      if (data.hasOwnProperty('locationCode')) {
        obj['locationCode'] = ApiClient.convertToType(data['locationCode'], 'String');
      }
      if (data.hasOwnProperty('locationName')) {
        obj['locationName'] = ApiClient.convertToType(data['locationName'], 'String');
      }
      if (data.hasOwnProperty('maxValidationsInPass')) {
        obj['maxValidationsInPass'] = ApiClient.convertToType(data['maxValidationsInPass'], 'Number');
      }
      if (data.hasOwnProperty('modifiedBy')) {
        obj['modifiedBy'] = UserDTO.constructFromObject(data['modifiedBy']);
      }
      if (data.hasOwnProperty('modifiedDate')) {
        obj['modifiedDate'] = ApiClient.convertToType(data['modifiedDate'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('packageProductId')) {
        obj['packageProductId'] = ApiClient.convertToType(data['packageProductId'], 'String');
      }
      if (data.hasOwnProperty('price')) {
        obj['price'] = ApiClient.convertToType(data['price'], 'Number');
      }
      if (data.hasOwnProperty('printType')) {
        obj['printType'] = ApiClient.convertToType(data['printType'], 'String');
      }
      if (data.hasOwnProperty('productId')) {
        obj['productId'] = ApiClient.convertToType(data['productId'], 'String');
      }
      if (data.hasOwnProperty('rechargePrice')) {
        obj['rechargePrice'] = ApiClient.convertToType(data['rechargePrice'], 'Number');
      }
      if (data.hasOwnProperty('retailPrice')) {
        obj['retailPrice'] = ApiClient.convertToType(data['retailPrice'], 'Number');
      }
      if (data.hasOwnProperty('sku')) {
        obj['sku'] = ApiClient.convertToType(data['sku'], 'String');
      }
      if (data.hasOwnProperty('subProductId')) {
        obj['subProductId'] = ApiClient.convertToType(data['subProductId'], 'String');
      }
      if (data.hasOwnProperty('tags')) {
        obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
      }
      if (data.hasOwnProperty('timezone')) {
        obj['timezone'] = ApiClient.convertToType(data['timezone'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('validValue')) {
        obj['validValue'] = ApiClient.convertToType(data['validValue'], 'Number');
      }
      if (data.hasOwnProperty('validationRules')) {
        obj['validationRules'] = ApiClient.convertToType(data['validationRules'], [Rule]);
      }
      if (data.hasOwnProperty('validationTag')) {
        obj['validationTag'] = ApiClient.convertToType(data['validationTag'], 'String');
      }
      if (data.hasOwnProperty('vendor')) {
        obj['vendor'] = VendorDTO.constructFromObject(data['vendor']);
      }
      if (data.hasOwnProperty('vendorAccountId')) {
        obj['vendorAccountId'] = ApiClient.convertToType(data['vendorAccountId'], 'String');
      }
      if (data.hasOwnProperty('vendorSku')) {
        obj['vendorSku'] = ApiClient.convertToType(data['vendorSku'], 'String');
      }
      if (data.hasOwnProperty('voucherPattern')) {
        obj['voucherPattern'] = VoucherPattern.constructFromObject(data['voucherPattern']);
      }
      if (data.hasOwnProperty('voucherType')) {
        obj['voucherType'] = ApiClient.convertToType(data['voucherType'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Boolean} allowRecharge
   */
  exports.prototype['allowRecharge'] = undefined;
  /**
   * @member {String} countryCode
   */
  exports.prototype['countryCode'] = undefined;
  /**
   * @member {module:model/SimpleProductDTO.CustomerTypeEnum} customerType
   */
  exports.prototype['customerType'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Array.<module:model/SimpleProductConnectionDTO>} includes
   */
  exports.prototype['includes'] = undefined;
  /**
   * @member {String} locationCode
   */
  exports.prototype['locationCode'] = undefined;
  /**
   * @member {String} locationName
   */
  exports.prototype['locationName'] = undefined;
  /**
   * @member {Number} maxValidationsInPass
   */
  exports.prototype['maxValidationsInPass'] = undefined;
  /**
   * @member {module:model/UserDTO} modifiedBy
   */
  exports.prototype['modifiedBy'] = undefined;
  /**
   * @member {String} modifiedDate
   */
  exports.prototype['modifiedDate'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} packageProductId
   */
  exports.prototype['packageProductId'] = undefined;
  /**
   * @member {Number} price
   */
  exports.prototype['price'] = undefined;
  /**
   * @member {module:model/SimpleProductDTO.PrintTypeEnum} printType
   */
  exports.prototype['printType'] = undefined;
  /**
   * @member {String} productId
   */
  exports.prototype['productId'] = undefined;
  /**
   * @member {Number} rechargePrice
   */
  exports.prototype['rechargePrice'] = undefined;
  /**
   * @member {Number} retailPrice
   */
  exports.prototype['retailPrice'] = undefined;
  /**
   * @member {String} sku
   */
  exports.prototype['sku'] = undefined;
  /**
   * @member {String} subProductId
   */
  exports.prototype['subProductId'] = undefined;
  /**
   * @member {Array.<String>} tags
   */
  exports.prototype['tags'] = undefined;
  /**
   * @member {String} timezone
   */
  exports.prototype['timezone'] = undefined;
  /**
   * @member {module:model/SimpleProductDTO.TypeEnum} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {Number} validValue
   */
  exports.prototype['validValue'] = undefined;
  /**
   * @member {Array.<module:model/Rule>} validationRules
   */
  exports.prototype['validationRules'] = undefined;
  /**
   * @member {String} validationTag
   */
  exports.prototype['validationTag'] = undefined;
  /**
   * @member {module:model/VendorDTO} vendor
   */
  exports.prototype['vendor'] = undefined;
  /**
   * @member {String} vendorAccountId
   */
  exports.prototype['vendorAccountId'] = undefined;
  /**
   * @member {String} vendorSku
   */
  exports.prototype['vendorSku'] = undefined;
  /**
   * @member {module:model/VoucherPattern} voucherPattern
   */
  exports.prototype['voucherPattern'] = undefined;
  /**
   * @member {module:model/SimpleProductDTO.VoucherTypeEnum} voucherType
   */
  exports.prototype['voucherType'] = undefined;


  /**
   * Allowed values for the <code>customerType</code> property.
   * @enum {String}
   * @readonly
   */
  exports.CustomerTypeEnum = {
    /**
     * value: "ADULT"
     * @const
     */
    "ADULT": "ADULT",
    /**
     * value: "CHILD"
     * @const
     */
    "CHILD": "CHILD",
    /**
     * value: "SENIOR"
     * @const
     */
    "SENIOR": "SENIOR"  };

  /**
   * Allowed values for the <code>printType</code> property.
   * @enum {String}
   * @readonly
   */
  exports.PrintTypeEnum = {
    /**
     * value: "AUTO_PRINT"
     * @const
     */
    "AUTO_PRINT": "AUTO_PRINT",
    /**
     * value: "NOT_PRINTABLE"
     * @const
     */
    "NOT_PRINTABLE": "NOT_PRINTABLE"  };

  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "BASIC_SINGLE"
     * @const
     */
    "BASIC_SINGLE": "BASIC_SINGLE",
    /**
     * value: "BASIC_VALID_HOURS"
     * @const
     */
    "BASIC_VALID_HOURS": "BASIC_VALID_HOURS",
    /**
     * value: "PASS_LIMITED"
     * @const
     */
    "PASS_LIMITED": "PASS_LIMITED",
    /**
     * value: "PASS_UNLIMITED"
     * @const
     */
    "PASS_UNLIMITED": "PASS_UNLIMITED",
    /**
     * value: "PASS_CALENDAR"
     * @const
     */
    "PASS_CALENDAR": "PASS_CALENDAR",
    /**
     * value: "FLEXPASS"
     * @const
     */
    "FLEXPASS": "FLEXPASS",
    /**
     * value: "PASS_CURRENCY"
     * @const
     */
    "PASS_CURRENCY": "PASS_CURRENCY"  };

  /**
   * Allowed values for the <code>voucherType</code> property.
   * @enum {String}
   * @readonly
   */
  exports.VoucherTypeEnum = {
    /**
     * value: "DEFAULT"
     * @const
     */
    "DEFAULT": "DEFAULT",
    /**
     * value: "CUSTOM"
     * @const
     */
    "CUSTOM": "CUSTOM"  };


  return exports;
}));


