/**
 * PassHub API
 * PassHub API documentation
 *
 * OpenAPI spec version: 1.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SuggestedOrderItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SuggestedOrderItem'));
  } else {
    // Browser globals (root is window)
    if (!root.PassHubApi) {
      root.PassHubApi = {};
    }
    root.PassHubApi.SuggestedOrder = factory(root.PassHubApi.ApiClient, root.PassHubApi.SuggestedOrderItem);
  }
}(this, function(ApiClient, SuggestedOrderItem) {
  'use strict';




  /**
   * The SuggestedOrder model module.
   * @module model/SuggestedOrder
   * @version 1.1
   */

  /**
   * Constructs a new <code>SuggestedOrder</code>.
   * @alias module:model/SuggestedOrder
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>SuggestedOrder</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SuggestedOrder} obj Optional instance to populate.
   * @return {module:model/SuggestedOrder} The populated <code>SuggestedOrder</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('items')) {
        obj['items'] = ApiClient.convertToType(data['items'], [SuggestedOrderItem]);
      }
      if (data.hasOwnProperty('orderId')) {
        obj['orderId'] = ApiClient.convertToType(data['orderId'], 'String');
      }
      if (data.hasOwnProperty('originator')) {
        obj['originator'] = ApiClient.convertToType(data['originator'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Array.<module:model/SuggestedOrderItem>} items
   */
  exports.prototype['items'] = undefined;
  /**
   * @member {String} orderId
   */
  exports.prototype['orderId'] = undefined;
  /**
   * @member {String} originator
   */
  exports.prototype['originator'] = undefined;



  return exports;
}));


