/**
 * PassHub API
 * PassHub API documentation
 *
 * OpenAPI spec version: 1.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PassHubApi) {
      root.PassHubApi = {};
    }
    root.PassHubApi.ValidationItemStatusDTO = factory(root.PassHubApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ValidationItemStatusDTO model module.
   * @module model/ValidationItemStatusDTO
   * @version 1.1
   */

  /**
   * Constructs a new <code>ValidationItemStatusDTO</code>.
   * @alias module:model/ValidationItemStatusDTO
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>ValidationItemStatusDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ValidationItemStatusDTO} obj Optional instance to populate.
   * @return {module:model/ValidationItemStatusDTO} The populated <code>ValidationItemStatusDTO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('balance')) {
        obj['balance'] = ApiClient.convertToType(data['balance'], 'Number');
      }
      if (data.hasOwnProperty('expiryDate')) {
        obj['expiryDate'] = ApiClient.convertToType(data['expiryDate'], 'String');
      }
      if (data.hasOwnProperty('maxUseCount')) {
        obj['maxUseCount'] = ApiClient.convertToType(data['maxUseCount'], 'Number');
      }
      if (data.hasOwnProperty('maxUseHours')) {
        obj['maxUseHours'] = ApiClient.convertToType(data['maxUseHours'], 'Number');
      }
      if (data.hasOwnProperty('startDate')) {
        obj['startDate'] = ApiClient.convertToType(data['startDate'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('usedCount')) {
        obj['usedCount'] = ApiClient.convertToType(data['usedCount'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} balance
   */
  exports.prototype['balance'] = undefined;
  /**
   * @member {String} expiryDate
   */
  exports.prototype['expiryDate'] = undefined;
  /**
   * @member {Number} maxUseCount
   */
  exports.prototype['maxUseCount'] = undefined;
  /**
   * @member {Number} maxUseHours
   */
  exports.prototype['maxUseHours'] = undefined;
  /**
   * @member {String} startDate
   */
  exports.prototype['startDate'] = undefined;
  /**
   * @member {module:model/ValidationItemStatusDTO.TypeEnum} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {Number} usedCount
   */
  exports.prototype['usedCount'] = undefined;


  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "BASIC_SINGLE"
     * @const
     */
    "BASIC_SINGLE": "BASIC_SINGLE",
    /**
     * value: "BASIC_VALID_HOURS"
     * @const
     */
    "BASIC_VALID_HOURS": "BASIC_VALID_HOURS",
    /**
     * value: "PASS_LIMITED"
     * @const
     */
    "PASS_LIMITED": "PASS_LIMITED",
    /**
     * value: "PASS_UNLIMITED"
     * @const
     */
    "PASS_UNLIMITED": "PASS_UNLIMITED",
    /**
     * value: "PASS_CALENDAR"
     * @const
     */
    "PASS_CALENDAR": "PASS_CALENDAR",
    /**
     * value: "FLEXPASS"
     * @const
     */
    "FLEXPASS": "FLEXPASS",
    /**
     * value: "PASS_CURRENCY"
     * @const
     */
    "PASS_CURRENCY": "PASS_CURRENCY"  };


  return exports;
}));


