/**
 * PassHub API
 * PassHub API documentation
 *
 * OpenAPI spec version: 1.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ValidationItemStatusDTO'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ValidationItemStatusDTO'));
  } else {
    // Browser globals (root is window)
    if (!root.PassHubApi) {
      root.PassHubApi = {};
    }
    root.PassHubApi.ValidationResultEntry = factory(root.PassHubApi.ApiClient, root.PassHubApi.ValidationItemStatusDTO);
  }
}(this, function(ApiClient, ValidationItemStatusDTO) {
  'use strict';




  /**
   * The ValidationResultEntry model module.
   * @module model/ValidationResultEntry
   * @version 1.1
   */

  /**
   * Constructs a new <code>ValidationResultEntry</code>.
   * @alias module:model/ValidationResultEntry
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>ValidationResultEntry</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ValidationResultEntry} obj Optional instance to populate.
   * @return {module:model/ValidationResultEntry} The populated <code>ValidationResultEntry</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('customerName')) {
        obj['customerName'] = ApiClient.convertToType(data['customerName'], 'String');
      }
      if (data.hasOwnProperty('customerType')) {
        obj['customerType'] = ApiClient.convertToType(data['customerType'], 'String');
      }
      if (data.hasOwnProperty('customerUid')) {
        obj['customerUid'] = ApiClient.convertToType(data['customerUid'], 'String');
      }
      if (data.hasOwnProperty('productName')) {
        obj['productName'] = ApiClient.convertToType(data['productName'], 'String');
      }
      if (data.hasOwnProperty('productSku')) {
        obj['productSku'] = ApiClient.convertToType(data['productSku'], 'String');
      }
      if (data.hasOwnProperty('quantity')) {
        obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ValidationItemStatusDTO.constructFromObject(data['status']);
      }
    }
    return obj;
  }

  /**
   * @member {String} customerName
   */
  exports.prototype['customerName'] = undefined;
  /**
   * @member {module:model/ValidationResultEntry.CustomerTypeEnum} customerType
   */
  exports.prototype['customerType'] = undefined;
  /**
   * @member {String} customerUid
   */
  exports.prototype['customerUid'] = undefined;
  /**
   * @member {String} productName
   */
  exports.prototype['productName'] = undefined;
  /**
   * @member {String} productSku
   */
  exports.prototype['productSku'] = undefined;
  /**
   * @member {Number} quantity
   */
  exports.prototype['quantity'] = undefined;
  /**
   * @member {module:model/ValidationItemStatusDTO} status
   */
  exports.prototype['status'] = undefined;


  /**
   * Allowed values for the <code>customerType</code> property.
   * @enum {String}
   * @readonly
   */
  exports.CustomerTypeEnum = {
    /**
     * value: "ADULT"
     * @const
     */
    "ADULT": "ADULT",
    /**
     * value: "CHILD"
     * @const
     */
    "CHILD": "CHILD",
    /**
     * value: "SENIOR"
     * @const
     */
    "SENIOR": "SENIOR"  };


  return exports;
}));


