/**
 * PassHub API
 * PassHub API documentation
 *
 * OpenAPI spec version: 1.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ProductSuggestion', 'model/RechargePrompt', 'model/SuggestedOrder', 'model/UniversalAttribute', 'model/ValidationResultEntry'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ProductSuggestion'), require('./RechargePrompt'), require('./SuggestedOrder'), require('./UniversalAttribute'), require('./ValidationResultEntry'));
  } else {
    // Browser globals (root is window)
    if (!root.PassHubApi) {
      root.PassHubApi = {};
    }
    root.PassHubApi.ValidationResult = factory(root.PassHubApi.ApiClient, root.PassHubApi.ProductSuggestion, root.PassHubApi.RechargePrompt, root.PassHubApi.SuggestedOrder, root.PassHubApi.UniversalAttribute, root.PassHubApi.ValidationResultEntry);
  }
}(this, function(ApiClient, ProductSuggestion, RechargePrompt, SuggestedOrder, UniversalAttribute, ValidationResultEntry) {
  'use strict';




  /**
   * The ValidationResult model module.
   * @module model/ValidationResult
   * @version 1.1
   */

  /**
   * Constructs a new <code>ValidationResult</code>.
   * @alias module:model/ValidationResult
   * @class
   */
  var exports = function() {
    var _this = this;

















  };

  /**
   * Constructs a <code>ValidationResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ValidationResult} obj Optional instance to populate.
   * @return {module:model/ValidationResult} The populated <code>ValidationResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('canSkipExpiryCheck')) {
        obj['canSkipExpiryCheck'] = ApiClient.convertToType(data['canSkipExpiryCheck'], 'Boolean');
      }
      if (data.hasOwnProperty('contractHolderId')) {
        obj['contractHolderId'] = ApiClient.convertToType(data['contractHolderId'], 'String');
      }
      if (data.hasOwnProperty('contractHolderName')) {
        obj['contractHolderName'] = ApiClient.convertToType(data['contractHolderName'], 'String');
      }
      if (data.hasOwnProperty('errorCode')) {
        obj['errorCode'] = ApiClient.convertToType(data['errorCode'], 'String');
      }
      if (data.hasOwnProperty('extra')) {
        obj['extra'] = ApiClient.convertToType(data['extra'], {'String': 'String'});
      }
      if (data.hasOwnProperty('meta')) {
        obj['meta'] = ApiClient.convertToType(data['meta'], [UniversalAttribute]);
      }
      if (data.hasOwnProperty('printStatus')) {
        obj['printStatus'] = ApiClient.convertToType(data['printStatus'], 'String');
      }
      if (data.hasOwnProperty('recharge')) {
        obj['recharge'] = RechargePrompt.constructFromObject(data['recharge']);
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('suggestedOrderItems')) {
        obj['suggestedOrderItems'] = ApiClient.convertToType(data['suggestedOrderItems'], [SuggestedOrder]);
      }
      if (data.hasOwnProperty('suggestedProducts')) {
        obj['suggestedProducts'] = ApiClient.convertToType(data['suggestedProducts'], [ProductSuggestion]);
      }
      if (data.hasOwnProperty('transactionTag')) {
        obj['transactionTag'] = ApiClient.convertToType(data['transactionTag'], 'String');
      }
      if (data.hasOwnProperty('validation')) {
        obj['validation'] = ApiClient.convertToType(data['validation'], [ValidationResultEntry]);
      }
      if (data.hasOwnProperty('validationDate')) {
        obj['validationDate'] = ApiClient.convertToType(data['validationDate'], 'String');
      }
      if (data.hasOwnProperty('voucherId')) {
        obj['voucherId'] = ApiClient.convertToType(data['voucherId'], 'String');
      }
      if (data.hasOwnProperty('waitingPeriodPending')) {
        obj['waitingPeriodPending'] = ApiClient.convertToType(data['waitingPeriodPending'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Boolean} canSkipExpiryCheck
   */
  exports.prototype['canSkipExpiryCheck'] = undefined;
  /**
   * @member {String} contractHolderId
   */
  exports.prototype['contractHolderId'] = undefined;
  /**
   * @member {String} contractHolderName
   */
  exports.prototype['contractHolderName'] = undefined;
  /**
   * @member {module:model/ValidationResult.ErrorCodeEnum} errorCode
   */
  exports.prototype['errorCode'] = undefined;
  /**
   * @member {Object.<String, String>} extra
   */
  exports.prototype['extra'] = undefined;
  /**
   * @member {Array.<module:model/UniversalAttribute>} meta
   */
  exports.prototype['meta'] = undefined;
  /**
   * @member {module:model/ValidationResult.PrintStatusEnum} printStatus
   */
  exports.prototype['printStatus'] = undefined;
  /**
   * @member {module:model/RechargePrompt} recharge
   */
  exports.prototype['recharge'] = undefined;
  /**
   * @member {module:model/ValidationResult.StatusEnum} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {Array.<module:model/SuggestedOrder>} suggestedOrderItems
   */
  exports.prototype['suggestedOrderItems'] = undefined;
  /**
   * @member {Array.<module:model/ProductSuggestion>} suggestedProducts
   */
  exports.prototype['suggestedProducts'] = undefined;
  /**
   * @member {String} transactionTag
   */
  exports.prototype['transactionTag'] = undefined;
  /**
   * @member {Array.<module:model/ValidationResultEntry>} validation
   */
  exports.prototype['validation'] = undefined;
  /**
   * @member {String} validationDate
   */
  exports.prototype['validationDate'] = undefined;
  /**
   * @member {String} voucherId
   */
  exports.prototype['voucherId'] = undefined;
  /**
   * @member {Number} waitingPeriodPending
   */
  exports.prototype['waitingPeriodPending'] = undefined;


  /**
   * Allowed values for the <code>errorCode</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ErrorCodeEnum = {
    /**
     * value: "VALIDATION_ID_NOT_FOUND"
     * @const
     */
    "VALIDATION_ID_NOT_FOUND": "VALIDATION_ID_NOT_FOUND",
    /**
     * value: "REQUESTED_PRODUCT_NOT_FOUND"
     * @const
     */
    "REQUESTED_PRODUCT_NOT_FOUND": "REQUESTED_PRODUCT_NOT_FOUND",
    /**
     * value: "REQUESTED_PRODUCT_USED"
     * @const
     */
    "REQUESTED_PRODUCT_USED": "REQUESTED_PRODUCT_USED",
    /**
     * value: "VALIDATION_FAILED"
     * @const
     */
    "VALIDATION_FAILED": "VALIDATION_FAILED",
    /**
     * value: "INSUFFICIENT_CURRENCY_AMOUNT"
     * @const
     */
    "INSUFFICIENT_CURRENCY_AMOUNT": "INSUFFICIENT_CURRENCY_AMOUNT",
    /**
     * value: "NOT_VALIDATABLE_PRODUCT"
     * @const
     */
    "NOT_VALIDATABLE_PRODUCT": "NOT_VALIDATABLE_PRODUCT",
    /**
     * value: "MAX_NUMBER_OF_USES_REACHED"
     * @const
     */
    "MAX_NUMBER_OF_USES_REACHED": "MAX_NUMBER_OF_USES_REACHED",
    /**
     * value: "VOUCHER_EXPIRED"
     * @const
     */
    "VOUCHER_EXPIRED": "VOUCHER_EXPIRED",
    /**
     * value: "VALIDATION_BLOCKED_DATES"
     * @const
     */
    "VALIDATION_BLOCKED_DATES": "VALIDATION_BLOCKED_DATES",
    /**
     * value: "VALIDATION_BLOCKED_TIME"
     * @const
     */
    "VALIDATION_BLOCKED_TIME": "VALIDATION_BLOCKED_TIME",
    /**
     * value: "VALIDATION_BLOCKED_DAYS"
     * @const
     */
    "VALIDATION_BLOCKED_DAYS": "VALIDATION_BLOCKED_DAYS",
    /**
     * value: "SYSTEMS_SYNC_FAILED"
     * @const
     */
    "SYSTEMS_SYNC_FAILED": "SYSTEMS_SYNC_FAILED",
    /**
     * value: "VALIDATIONS_PER_DAY_EXCEEDED"
     * @const
     */
    "VALIDATIONS_PER_DAY_EXCEEDED": "VALIDATIONS_PER_DAY_EXCEEDED",
    /**
     * value: "WAITING_PERIOD_NOT_EXPIRED"
     * @const
     */
    "WAITING_PERIOD_NOT_EXPIRED": "WAITING_PERIOD_NOT_EXPIRED"  };

  /**
   * Allowed values for the <code>printStatus</code> property.
   * @enum {String}
   * @readonly
   */
  exports.PrintStatusEnum = {
    /**
     * value: "NOT_PRINTABLE"
     * @const
     */
    "NOT_PRINTABLE": "NOT_PRINTABLE",
    /**
     * value: "PRINTED"
     * @const
     */
    "PRINTED": "PRINTED",
    /**
     * value: "NEED_PRINTING"
     * @const
     */
    "NEED_PRINTING": "NEED_PRINTING"  };

  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "SUCCESS"
     * @const
     */
    "SUCCESS": "SUCCESS",
    /**
     * value: "CLARIFY"
     * @const
     */
    "CLARIFY": "CLARIFY",
    /**
     * value: "FAILURE"
     * @const
     */
    "FAILURE": "FAILURE",
    /**
     * value: "CLARIFY_ORDER"
     * @const
     */
    "CLARIFY_ORDER": "CLARIFY_ORDER",
    /**
     * value: "CLARIFY_ITEM"
     * @const
     */
    "CLARIFY_ITEM": "CLARIFY_ITEM"  };


  return exports;
}));


