/**
 * PassHub API
 * PassHub API documentation
 *
 * OpenAPI spec version: 1.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/UserCompactDTO'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./UserCompactDTO'));
  } else {
    // Browser globals (root is window)
    if (!root.PassHubApi) {
      root.PassHubApi = {};
    }
    root.PassHubApi.VendorDetailDTO = factory(root.PassHubApi.ApiClient, root.PassHubApi.UserCompactDTO);
  }
}(this, function(ApiClient, UserCompactDTO) {
  'use strict';




  /**
   * The VendorDetailDTO model module.
   * @module model/VendorDetailDTO
   * @version 1.1
   */

  /**
   * Constructs a new <code>VendorDetailDTO</code>.
   * @alias module:model/VendorDetailDTO
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>VendorDetailDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VendorDetailDTO} obj Optional instance to populate.
   * @return {module:model/VendorDetailDTO} The populated <code>VendorDetailDTO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('allowManual')) {
        obj['allowManual'] = ApiClient.convertToType(data['allowManual'], 'Boolean');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('users')) {
        obj['users'] = ApiClient.convertToType(data['users'], [UserCompactDTO]);
      }
    }
    return obj;
  }

  /**
   * @member {Boolean} allowManual
   */
  exports.prototype['allowManual'] = undefined;
  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {Array.<module:model/UserCompactDTO>} users
   */
  exports.prototype['users'] = undefined;



  return exports;
}));


