/**
 * PassHub API
 * PassHub API documentation
 *
 * OpenAPI spec version: 1.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PassHubApi) {
      root.PassHubApi = {};
    }
    root.PassHubApi.VoucherPattern = factory(root.PassHubApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The VoucherPattern model module.
   * @module model/VoucherPattern
   * @version 1.1
   */

  /**
   * Constructs a new <code>VoucherPattern</code>.
   * @alias module:model/VoucherPattern
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>VoucherPattern</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VoucherPattern} obj Optional instance to populate.
   * @return {module:model/VoucherPattern} The populated <code>VoucherPattern</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('bodyLength')) {
        obj['bodyLength'] = ApiClient.convertToType(data['bodyLength'], 'Number');
      }
      if (data.hasOwnProperty('bodyType')) {
        obj['bodyType'] = ApiClient.convertToType(data['bodyType'], 'String');
      }
      if (data.hasOwnProperty('patternProductId')) {
        obj['patternProductId'] = ApiClient.convertToType(data['patternProductId'], 'Number');
      }
      if (data.hasOwnProperty('prefix')) {
        obj['prefix'] = ApiClient.convertToType(data['prefix'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} bodyLength
   */
  exports.prototype['bodyLength'] = undefined;
  /**
   * @member {module:model/VoucherPattern.BodyTypeEnum} bodyType
   */
  exports.prototype['bodyType'] = undefined;
  /**
   * @member {Number} patternProductId
   */
  exports.prototype['patternProductId'] = undefined;
  /**
   * @member {String} prefix
   */
  exports.prototype['prefix'] = undefined;


  /**
   * Allowed values for the <code>bodyType</code> property.
   * @enum {String}
   * @readonly
   */
  exports.BodyTypeEnum = {
    /**
     * value: "NUMERIC"
     * @const
     */
    "NUMERIC": "NUMERIC",
    /**
     * value: "ALPHA_NUMERIC"
     * @const
     */
    "ALPHA_NUMERIC": "ALPHA_NUMERIC"  };


  return exports;
}));


