/**
 * PassHub API
 * PassHub API documentation
 *
 * OpenAPI spec version: 1.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Address', 'model/Condition', 'model/DeliveryDTO', 'model/ExtraValidationParamDTO', 'model/GenericStatusDTO', 'model/GroupEntryDTO', 'model/JSONObject', 'model/MapOfstringAndstring', 'model/OrderItem', 'model/OrderNoteParamDTO', 'model/OrderRecordDTO', 'model/OrderRecordExtendDTO', 'model/ProductDTO', 'model/ProductSuggestion', 'model/RechargeProductGroup', 'model/RechargePrompt', 'model/RechargePromptEntry', 'model/Rule', 'model/SimpleConnectedProductDTO', 'model/SimpleMetadata', 'model/SimpleProductConnectionDTO', 'model/SimpleProductDTO', 'model/SuggestedOrder', 'model/SuggestedOrderItem', 'model/UniversalAttribute', 'model/UserCompactDTO', 'model/UserDTO', 'model/ValidationItemStatusDTO', 'model/ValidationResult', 'model/ValidationResultEntry', 'model/VendorDTO', 'model/VendorDetailDTO', 'model/VoucherPattern', 'api/OrderRecordResourceApi', 'api/ProductResourceApi', 'api/VendorResourceApi', 'api/VoucherResourceApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Address'), require('./model/Condition'), require('./model/DeliveryDTO'), require('./model/ExtraValidationParamDTO'), require('./model/GenericStatusDTO'), require('./model/GroupEntryDTO'), require('./model/JSONObject'), require('./model/MapOfstringAndstring'), require('./model/OrderItem'), require('./model/OrderNoteParamDTO'), require('./model/OrderRecordDTO'), require('./model/OrderRecordExtendDTO'), require('./model/ProductDTO'), require('./model/ProductSuggestion'), require('./model/RechargeProductGroup'), require('./model/RechargePrompt'), require('./model/RechargePromptEntry'), require('./model/Rule'), require('./model/SimpleConnectedProductDTO'), require('./model/SimpleMetadata'), require('./model/SimpleProductConnectionDTO'), require('./model/SimpleProductDTO'), require('./model/SuggestedOrder'), require('./model/SuggestedOrderItem'), require('./model/UniversalAttribute'), require('./model/UserCompactDTO'), require('./model/UserDTO'), require('./model/ValidationItemStatusDTO'), require('./model/ValidationResult'), require('./model/ValidationResultEntry'), require('./model/VendorDTO'), require('./model/VendorDetailDTO'), require('./model/VoucherPattern'), require('./api/OrderRecordResourceApi'), require('./api/ProductResourceApi'), require('./api/VendorResourceApi'), require('./api/VoucherResourceApi'));
  }
}(function(ApiClient, Address, Condition, DeliveryDTO, ExtraValidationParamDTO, GenericStatusDTO, GroupEntryDTO, JSONObject, MapOfstringAndstring, OrderItem, OrderNoteParamDTO, OrderRecordDTO, OrderRecordExtendDTO, ProductDTO, ProductSuggestion, RechargeProductGroup, RechargePrompt, RechargePromptEntry, Rule, SimpleConnectedProductDTO, SimpleMetadata, SimpleProductConnectionDTO, SimpleProductDTO, SuggestedOrder, SuggestedOrderItem, UniversalAttribute, UserCompactDTO, UserDTO, ValidationItemStatusDTO, ValidationResult, ValidationResultEntry, VendorDTO, VendorDetailDTO, VoucherPattern, OrderRecordResourceApi, ProductResourceApi, VendorResourceApi, VoucherResourceApi) {
  'use strict';

  /**
   * PassHub_API_documentation.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var PassHubApi = require('index'); // See note below*.
   * var xxxSvc = new PassHubApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new PassHubApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new PassHubApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new PassHubApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.1
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Address model constructor.
     * @property {module:model/Address}
     */
    Address: Address,
    /**
     * The Condition model constructor.
     * @property {module:model/Condition}
     */
    Condition: Condition,
    /**
     * The DeliveryDTO model constructor.
     * @property {module:model/DeliveryDTO}
     */
    DeliveryDTO: DeliveryDTO,
    /**
     * The ExtraValidationParamDTO model constructor.
     * @property {module:model/ExtraValidationParamDTO}
     */
    ExtraValidationParamDTO: ExtraValidationParamDTO,
    /**
     * The GenericStatusDTO model constructor.
     * @property {module:model/GenericStatusDTO}
     */
    GenericStatusDTO: GenericStatusDTO,
    /**
     * The GroupEntryDTO model constructor.
     * @property {module:model/GroupEntryDTO}
     */
    GroupEntryDTO: GroupEntryDTO,
    /**
     * The JSONObject model constructor.
     * @property {module:model/JSONObject}
     */
    JSONObject: JSONObject,
    /**
     * The MapOfstringAndstring model constructor.
     * @property {module:model/MapOfstringAndstring}
     */
    MapOfstringAndstring: MapOfstringAndstring,
    /**
     * The OrderItem model constructor.
     * @property {module:model/OrderItem}
     */
    OrderItem: OrderItem,
    /**
     * The OrderNoteParamDTO model constructor.
     * @property {module:model/OrderNoteParamDTO}
     */
    OrderNoteParamDTO: OrderNoteParamDTO,
    /**
     * The OrderRecordDTO model constructor.
     * @property {module:model/OrderRecordDTO}
     */
    OrderRecordDTO: OrderRecordDTO,
    /**
     * The OrderRecordExtendDTO model constructor.
     * @property {module:model/OrderRecordExtendDTO}
     */
    OrderRecordExtendDTO: OrderRecordExtendDTO,
    /**
     * The ProductDTO model constructor.
     * @property {module:model/ProductDTO}
     */
    ProductDTO: ProductDTO,
    /**
     * The ProductSuggestion model constructor.
     * @property {module:model/ProductSuggestion}
     */
    ProductSuggestion: ProductSuggestion,
    /**
     * The RechargeProductGroup model constructor.
     * @property {module:model/RechargeProductGroup}
     */
    RechargeProductGroup: RechargeProductGroup,
    /**
     * The RechargePrompt model constructor.
     * @property {module:model/RechargePrompt}
     */
    RechargePrompt: RechargePrompt,
    /**
     * The RechargePromptEntry model constructor.
     * @property {module:model/RechargePromptEntry}
     */
    RechargePromptEntry: RechargePromptEntry,
    /**
     * The Rule model constructor.
     * @property {module:model/Rule}
     */
    Rule: Rule,
    /**
     * The SimpleConnectedProductDTO model constructor.
     * @property {module:model/SimpleConnectedProductDTO}
     */
    SimpleConnectedProductDTO: SimpleConnectedProductDTO,
    /**
     * The SimpleMetadata model constructor.
     * @property {module:model/SimpleMetadata}
     */
    SimpleMetadata: SimpleMetadata,
    /**
     * The SimpleProductConnectionDTO model constructor.
     * @property {module:model/SimpleProductConnectionDTO}
     */
    SimpleProductConnectionDTO: SimpleProductConnectionDTO,
    /**
     * The SimpleProductDTO model constructor.
     * @property {module:model/SimpleProductDTO}
     */
    SimpleProductDTO: SimpleProductDTO,
    /**
     * The SuggestedOrder model constructor.
     * @property {module:model/SuggestedOrder}
     */
    SuggestedOrder: SuggestedOrder,
    /**
     * The SuggestedOrderItem model constructor.
     * @property {module:model/SuggestedOrderItem}
     */
    SuggestedOrderItem: SuggestedOrderItem,
    /**
     * The UniversalAttribute model constructor.
     * @property {module:model/UniversalAttribute}
     */
    UniversalAttribute: UniversalAttribute,
    /**
     * The UserCompactDTO model constructor.
     * @property {module:model/UserCompactDTO}
     */
    UserCompactDTO: UserCompactDTO,
    /**
     * The UserDTO model constructor.
     * @property {module:model/UserDTO}
     */
    UserDTO: UserDTO,
    /**
     * The ValidationItemStatusDTO model constructor.
     * @property {module:model/ValidationItemStatusDTO}
     */
    ValidationItemStatusDTO: ValidationItemStatusDTO,
    /**
     * The ValidationResult model constructor.
     * @property {module:model/ValidationResult}
     */
    ValidationResult: ValidationResult,
    /**
     * The ValidationResultEntry model constructor.
     * @property {module:model/ValidationResultEntry}
     */
    ValidationResultEntry: ValidationResultEntry,
    /**
     * The VendorDTO model constructor.
     * @property {module:model/VendorDTO}
     */
    VendorDTO: VendorDTO,
    /**
     * The VendorDetailDTO model constructor.
     * @property {module:model/VendorDetailDTO}
     */
    VendorDetailDTO: VendorDetailDTO,
    /**
     * The VoucherPattern model constructor.
     * @property {module:model/VoucherPattern}
     */
    VoucherPattern: VoucherPattern,
    /**
     * The OrderRecordResourceApi service constructor.
     * @property {module:api/OrderRecordResourceApi}
     */
    OrderRecordResourceApi: OrderRecordResourceApi,
    /**
     * The ProductResourceApi service constructor.
     * @property {module:api/ProductResourceApi}
     */
    ProductResourceApi: ProductResourceApi,
    /**
     * The VendorResourceApi service constructor.
     * @property {module:api/VendorResourceApi}
     */
    VendorResourceApi: VendorResourceApi,
    /**
     * The VoucherResourceApi service constructor.
     * @property {module:api/VoucherResourceApi}
     */
    VoucherResourceApi: VoucherResourceApi
  };

  return exports;
}));
